version: '3.8'

services:
  # 1. ฐานข้อมูล PostgreSQL
  db:
    image: postgres:15
    container_name: lecture-db
    restart: always
    environment:
      POSTGRES_USER: admin        # ชื่อผู้ใช้
      POSTGRES_PASSWORD: password123 # รหัสผ่าน (จำอันนี้ไว้นะครับ)
      POSTGRES_DB: lecture_clubhouse_db # ชื่อฐานข้อมูล
    ports:
      - "5433:5432" # เปิดพอร์ตให้ NestJS เชื่อมต่อได้
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. (แถม) pgAdmin4 คือหน้าเว็บไว้ดูข้อมูลใน DB (คล้ายๆ PHPMyAdmin)
  pgadmin:
    image: dpage/pgadmin4
    container_name: lecture-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5433:5432" # เข้าผ่าน http://localhost:5050
    depends_on:
      - db

volumes:
  postgres_data: